# An Investigation of the numpy.random package in Python

## Numpy
NumPy, short for Numerical Python, is one of the most important fundamental packages for numerical computing in Python. Most computational packages providing scientific functionality use NumpPy’s array objects for data exchange.

### Here are some of the things you will find in NumPy:

1.	Ndarray, an efficient multidimensional array providing fast array-orientated arithmetic        operations and flexible broadcasting capabilities.
2.	Mathematical functions for fast operations and entire arrays of data without having to write loops. 
3.	Tools for reading /writing array data to disk and working with memory -mapped files.
4.	Linear algebra, random number generation, and Fourier transform capabilities.
5.	A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Because NumPy provides an easy-to-use C API, it is straightforward to pass data to external libraries written in low-level language and also for external libraries to return data to Python as NumPy arrays. This feature has made Python a language of choice for wrapping legacy C/C++/Fortran codebases and giving them a dynamic and easy-to-use interface.
One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. 

NumPy works with Python objects called multi-dimensional arrays. Arrays are basically collections of values, and they have one or more dimensions. NumPy array data structure is also called ndarray, short for n-dimensional array. An array with one dimension is called a vector and an array with two dimensions is called a matrix. Datasets are usually built as matrices and it is much easier to open those with NumPy instead of working with list of lists, for example.

### There are a number of reasons for this, as follows:
1.	NumPy internally stores data in a contiguous block of memory, independent of other built-in Pyhton objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays can also use much less memory than built-in Python sequences.
2.	NumPy operations perform complex computations on entire arrays without the need for loops.


In [1]:
# Consider a NumPy array of one million integers, and the equivqlent Python list
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
# Now let's multiply each sequence by 2:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 100 ms


In [9]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 2.66 s


### NumPy-based algorithms are generally 10 to 100 times faster , or more, as above, than their pure Python counterparts and use significantly less memory space. 

### numpy.random 

The numpy.random sub-package is used to generate random numbers and allows random sampling to take place.

Real random numbers are difficult to produce, so in practice, we use pseudo-random numbers. Pseudo-random numbers are sufficiently random for most intents and purposes, except for some very exceptional instances, such as very accurate simulations. The random-numbers-associated routines can be located in the NumPy random subpackage.

The numpy.random module supplements the built-in Python random with functions for efficiently generating whole arrays of same values from many kinds of probability distributions. for example you can get a 4 x 4 array of samples from the standard normal distribution using *normal

Another cool feature is the ability to create different arrays like random arrays: np.random.rand(3,4) will create a 3x4 array of random numbers between 0 and 1 while np.random.rand(7,6)*100 will create a 7x6 array of random numbers between 0 to 100; you can also define the size of the array in a different way: np.random.randint(10,size=(3,2)) creates an array the size of 3x2 with random numbers between 0 and 9. Remember that the last digit (10) is not included in the range when you use this syntax.
It’s also possible to create an array of all zeros: np.zeros(4,3) (4x3 array of all zeros) or ones np.ones((4)) (4x1 array of ones); you can the command np.full((3,2),8) to create a 3x2 array full of 8. You can, of course, change each and every one of these numbers to get the array you want.


In [6]:
import numpy as np
samp = np.random.normal(size=(3,3))


In [7]:
samp

array([[ 0.05038804, -0.7314969 ,  0.2654911 ],
       [ 1.21549817, -0.95655902, -1.40742094],
       [-0.46971657,  0.48111324,  0.18582194]])

### Simple random data

In [8]:
# numpy.random.rand
# Random values in a given shape.
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
np.random.rand(3,2)

array([[0.75848239, 0.05975689],
       [0.77378972, 0.71286411],
       [0.80898156, 0.25356927]])

In [9]:
# numpy.random.randn
# Using randn(), we can generate random samples from Standard, normal or Gaussian distribution centered around 0. For example, let’s generate 7 random numbers:
my_randn = np.random.randn(7)
my_randn


array([-0.36927144,  0.340748  ,  1.02273831,  0.21840785, -0.62872609,
        0.28202201,  0.19097352])

In [10]:
# When you plot the result will give us a normal distribution curve.

# Similarly, to generate a two-dimensional array of 3 rows and 5 columns, do this:
np.random.randn(3,5)
    
    

array([[-2.27842727, -0.48681505,  0.93658526,  1.82912755,  0.62543294],
       [-0.20322857, -0.00941695,  0.30743574, -0.85402399, -0.17526863],
       [-1.05828489,  0.85301207, -0.32024876, -0.87470377,  0.43343844]])

In [15]:
# Lastly, we can use the randint() function to generate an array of integers. The randint() function can take up to 3 arguments; the low(inclusive), high(exclusive) and size of the array.
np.random.randint(20) #generates a random integer exclusive of 20


3

In [12]:
np.random.randint(2, 20) #generates a random integer including 2 but excluding 20

17

In [13]:
np.random.randint(2, 20, 7) #generates 7 random integers including 2 but excluding 20

array([16, 18, 18, 16, 10, 11,  2])

In [22]:
arr = np.random.rand(25)# First, we generate a 1-d array of random 25 integers
arr

array([0.95948327, 0.23946691, 0.54729454, 0.28909015, 0.74728671,
       0.25670148, 0.88353808, 0.4271074 , 0.74066045, 0.43580013,
       0.2708154 , 0.44941082, 0.64540871, 0.52167736, 0.46034238,
       0.33960401, 0.05507762, 0.39845832, 0.87339203, 0.95972757,
       0.74445146, 0.54030429, 0.0013303 , 0.07126352, 0.8526706 ])

In [23]:
arr.reshape(5,5)# Then convert it to a 2-d array using the reshape() function
# The reshape() can only convert to equal number or rows and columns and must together be equal to equal to the number of elements. In the example above, arr contained 25 elements hence can only be reshaped to a 5X5 matrix.

array([[0.95948327, 0.23946691, 0.54729454, 0.28909015, 0.74728671],
       [0.25670148, 0.88353808, 0.4271074 , 0.74066045, 0.43580013],
       [0.2708154 , 0.44941082, 0.64540871, 0.52167736, 0.46034238],
       [0.33960401, 0.05507762, 0.39845832, 0.87339203, 0.95972757],
       [0.74445146, 0.54030429, 0.0013303 , 0.07126352, 0.8526706 ]])